# Generated by Django 5.1 on 2024-08-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='body',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
