# Generated by Django 5.1 on 2024-08-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageblogmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='', max_length=255)),
                ('blog_image', models.FileField(upload_to='')),
                ('blog_body', models.TextField()),
            ],
        ),
    ]
