# Generated by Django 5.1 on 2024-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='blog_image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
